In [3]:
import sys
import os

# the following code is to replace the current path
# with the package's path
current_path = os.getcwd()
current_path = current_path.replace('MagicFormula/exploratory_code','sigma-lib')
sys.path.insert(0,current_path)

# the package

from sigma_lib import awscloud

# Disable warnings
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

In [17]:
df_describe = servidor.client_execute(['describe','trade_da'])
df_describe.iloc[8].comment

'número de seqüência correspondente ao estado de direito vigente'

In [5]:
servidor = awscloud.server()

{
    "StartingInstances": [
        {
            "CurrentState": {
                "Code": 16,
                "Name": "running"
            },
            "InstanceId": "i-054971003af7a51b0",
            "PreviousState": {
                "Code": 16,
                "Name": "running"
            }
        }
    ]
}

In [9]:
servidor.client_execute([\
    '*',\
    'trade_da',\
    'tpmerc',\
    ['10'],\
    ['datneg','2021-12-01','2021-12-02']
])

,datneg,codneg,codisi,especi,tpmerc,dismes,preabe,premax,premin,preult,preexe,totneg,quatot,voltot,event1,event2,ajuste
0,2021-12-01,BPAN4,BRBPANACNPR1,PN N1,10,111,11.240797,11.513065,10.560126,10.637917,0.0,12607,5.760874e+06,63383493.00,NaN,NaN,0.972387
1,2021-12-01,HGLG11,BRHGLGCTF004,CI ER,10,239,159.540000,160.990000,159.540000,160.450000,0.0,5219,3.400100e+04,5441034.13,NaN,NaN,1.000000
2,2021-12-01,HGIC11,BRHGICCTF009,CI ER,10,109,105.000000,105.000000,105.000000,105.000000,0.0,2,2.000000e+00,210.00,NaN,NaN,1.000000
3,2021-12-01,HGFF11,BRHGFFCTF008,CI ER,10,130,67.190000,67.190000,65.130000,66.140000,0.0,2057,1.067500e+04,704867.10,NaN,NaN,1.000000
4,2021-12-01,HGCR11,BRHGCRCTF000,CI ER,10,214,101.650000,102.490000,100.210000,101.790000,0.0,1100,2.128500e+04,2156961.27,NaN,NaN,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2397,2021-12-02,NGRD3,BRNGRDACNOR3,ON NM,10,101,2.731669,2.801203,2.602536,2.721736,0.0,7673,2.500467e+06,6709688.00,NaN,NaN,0.993334
2398,2021-12-02,BCIA11,BRBCIACTF005,CI ER,10,180,82.990000,82.990000,81.000000,81.000000,0.0,188,4.497000e+03,367659.94,NaN,NaN,1.000000
2399,2021-12-02,NFLX34,BRNFLXBDR000,DRN,10,102,69.410000,70.660000,65.400000,70.660000,0.0,1032,1.069370e+05,7448187.43,NaN,NaN,1.000000
2400,2021-12-02,NOKI34,BRNOKIBDR005,DRN,10,100,31.560000,31.650000,31.470000,31.650000,0.0,3,7.000000e+00,220.83,NaN,NaN,1.000000
2401,2021-12-02,JDCO34,BRJDCOBDR001,DRN,10,100,490.000000,490.580000,474.290000,474.290000,0.0,32,3.874000e+03,1872403.50,NaN,NaN,1.000000